name: CI

on: [pull_request]

jobs:
  code_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: knip
        run: bun knip

      - name: lint
        run: bun lint

      - name: format
        run: bun format

      - name: typecheck
        run: bun typecheck

      - name: test
        run: bun test
